# Generated by Django 4.2.5 on 2023-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('members', models.ManyToManyField(blank=True, to='members.member')),
            ],
        ),
    ]
