# Generated by Django 4.2.5 on 2023-10-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_meal_mealmonth_all_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='number_of_meals',
            field=models.IntegerField(default=2),
        ),
    ]
