# Generated by Django 4.2.5 on 2023-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_meal_number_of_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.TextField(),
        ),
    ]
