# Generated by Django 4.2.5 on 2023-10-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('manager', '0005_alter_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joma_amount', models.IntegerField(default=0)),
                ('joma_date', models.TextField(blank=True)),
                ('joma_type', models.IntegerField(default=1)),
                ('joma_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('joma_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.mealmonth')),
            ],
        ),
    ]
